# Ejercicio N° 10


### El dataset ventas.xlsx contiene los registros de una serie de ventas realizadas en el último tiempo en un local de productos electrónicos. Por otra parte, cuenta con el dataset clientes_base.xlsx, el cual contiene información sobre los clientes registrados en dicho establecimiento.

* ¿Cuál fue el monto total de venta de productos iPad y MacBook?

* Realice la unión de ambos DataFrames utilizando la operación que considere más adecuada y la columna nombre_cliente como key. ¿Qué observa en el DataFrame resultante?

* Considerando que en clientes_base.xlsx los nombres de los clientes se encuentran exentos de errores ortográficos y tipográficos, ¿en qué porcentaje de los registros que conforman el dataset ventas.xlsx el nombre del cliente coincide con el de un cliente registrado?

* Teniendo en cuenta lo observado en los ítems anteriores, utilice herramientas de fuzzy joins para realizar la unión de ambos datasets. ¿De qué ciudad es el cliente que más compras realizó en el local?

In [1]:
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt

In [4]:
ventas = pd.read_excel('./datasets/ventas.xlsx')
ventas.set_index('id_venta',inplace=True)
ventas.head()

,nombre_cliente,producto,cantidad,precio_usd_producto
id_venta,,,,
C1,Juana Perez,Apple Watch Series 8,2,399
C2,Roberto Gomezz,Nintendo Switch,1,299
C3,Carla Gonzáles Cuispe,Bose QuietComfort 45,1,329
C4,Jorge Martinez,Acer Predator Helios 300,1,1599
C5,Mariano Rodriguéz,iPad Pro,1,1099

In [7]:
clientes=pd.read_excel('./datasets/clientes_base.xlsx')
clientes.set_index('id_cliente',inplace=True)
clientes.head()

                 nombre_cliente       ciudad                 email
id_cliente
1               Lucia Fernandez  Villa María      luciaf2@mail.com
2                  Carlos Gómez      Mendoza  carlosgomez@mail.com
3                  Andrés Pérez   Corrientes     andresp3@mail.com
4                 Roberto Gómez      Rosario       rgomez@mail.com
5           Roberto Gómez Acuña   Corrientes      robgoac@mail.com

* ¿Cuál fue el monto total de venta de productos iPad y MacBook?